### ISSUE TITLE
React error when specified CHANGELOG file does not exist

### ISSUE THREAD

**Issue by daneah** [RSC-Labs/backstage-changelog-plugin#2] opened 2023-11-03 11:26 UTC
When a CHANGELOG file does not exist where the plugin is looking, it results in an unrecoverable React error. It seems worth showing a friendly error on the tab and allowing users to navigate back to whatever else the component offers instead.

Further, during local development if I've added a `catalog.locations.target` in the app config that points to a component's `catalog-info.yaml` file (I think this is how I have to do it?), the plugin tries to look for a file with a calculated filename of `.../catalog-info.yamlCHANGELOG.md`:

```
[1] 2023-11-03T11:20:30.292Z backstage error Request failed with status 500 ENOENT: no such file or directory, open '/Users/dhillard/source/test-component/catalog-info.yamlCHANGELOG.md' type=errorHandler errno=-2 syscall=open code=ENOENT path=/Users/dhillard/source/test-component/catalog-info.yamlCHANGELOG.md stack=Error: ENOENT: no such file or directory, open '/Users/dhillard/source/test-component/catalog-info.yamlCHANGELOG.md'
[1]     at Object.openSync (node:fs:601:3)
[1]     at Object.readFileSync (node:fs:469:35)
[1]     at readChangelogFile (/Users/dhillard/source/backstage/node_modules/@rsc-labs/backstage-changelog-plugin-backend/dist/index.cjs.js:21:41)
[1]     at /Users/dhillard/source/backstage/node_modules/@rsc-labs/backstage-changelog-plugin-backend/dist/index.cjs.js:92:30
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

<img width="1086" alt="Screenshot 2023-11-03 at 07 21 42" src="https://github.com/RSC-Labs/backstage-changelog-plugin/assets/1808306/efe65dfc-0983-454c-864a-11f53aae2dad">

**Comment by alexhampu** [comment] 2023-11-03 13:22
This also happens to me when the CHANGELOG.md file is missing from a repository.

**Comment by radoslaw-sz** [comment] 2023-11-04 18:39
Thank you for raising this issue. I will take a look at it after a weekend.

**Comment by alexhampu** [comment] 2023-11-05 20:46
As an update, now I have the CHANGELOG.md in my repository, but haven't added any of the annotations added to the project's catalog file, however it still throws an error.

![image](https://github.com/RSC-Labs/backstage-changelog-plugin/assets/21214654/f700fa72-1cd1-4872-a3d1-1209a9de8b2c)

When looking over the backstage server logs, I have the following message:

```
{"code":"ENOENT","errno":-2,"level":"error","message":"Request failed with status 500 ENOENT: no such file or directory, open 'https://github.com/private-team/private-project/tree/master/CHANGELOG.md'","path":"https://github.com/private-team/private-project/tree/master/CHANGELOG.md","service":"backstage","stack":"Error: ENOENT: no such file or directory, open 'https://github.com/private-team/private-project/tree/master/CHANGELOG.md'\n at Object.openSync (node:fs:603:3)\n at Object.readFileSync (node:fs:471:35)\n at readChangelogFile (/app/node_modules/@rsc-labs/backstage-changelog-plugin-backend/dist/index.cjs.js:21:41)\n at /app/node_modules/@rsc-labs/backstage-changelog-plugin-backend/dist/index.cjs.js:92:30\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"open","type":"errorHandler"}
```

Does this plugin try to access the CHANGELOG.md by doing a get that URL? Because this won't work as the repository is private.

**Comment by jsidney** [comment] 2023-11-06 08:42
@alexhampu  - i had a similar issue, but when I explicitly added the annotation to my `catalog-info` it worked. 
so something like this:
```yaml
changelog-file-ref: "url:https://bitbucket.org/xxxx/xxxx/src/main/CHANGELOG.md"
```

**Comment by radoslaw-sz** [comment] 2023-11-06 17:55
Hi everyone,
New version landed - I have fixed unrecoverable situation with error on frontend. I do not have good idea how to handle that, it just shows error.
@daneah - like @jsidney  mentioned - you need to handle annotations in catalog-info.yaml, please check this code from README:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    backstage.io/source-location: "file:/home/backstage/backstage-changelog/examples/"
    changelog-file-ref: "url:https://github.com/RSC-Labs/backstage-changelog-plugin/tree/main/CHANGELOG.md"
    changelog-name: "CHANGELOG_CUSTOM_NAME.md"
```
Description how to use these annotations can be found here: https://github.com/RSC-Labs/backstage-changelog-plugin#backend-plugin

**Comment by radoslaw-sz** [comment] 2023-11-06 18:55
@alexhampu - when I created this plugin my idea was that if anyone wants to use it, then needs to properly configure it (e.g. CHANGELOG shall be accessible in any way, through "source-location" or other annotations (see above response).
I did not want to introduce new annotations like "feature on/off" to make it user friendly (in the best case scenario you can have only "backstage.io/source-location" which is used also for other features and this plugin can work automatically).
If you feel differently, of course please share you view on this :)

Regarding private repos which are non-accessible publicly - this can be interesting feature, right now it is not supported unfortunately...

If you would have any more problem with using it, please raise issues/questions.

**Comment by alexhampu** [comment] 2023-11-07 16:07
@radoslaw-sz I am just following the documentation:

> Plugin uses following logic:
> * If "changelog-file-ref" is provided it takes precedence over other options, so it is used for reading a Changelog
> * If not provided, then plugin check is "changelog-name" is provided. If yes, then it uses "backstage.io/source-location" as a location path together with "changelog-name"
> * If no above options are provided, plugin uses "backstage.io/source-location" for reading a file named "CHANGELOG.md".

So based on this, I don't need to add any annotation as the third option will be used by default. And I have a valid CHANGELOG.md file in my repository and the URL gets generated automatically. Without adding the annotation the link to the CHANGELOG.md file is generated fine, but the page is not working. To clarify, the repository is private, and backstage has access to it.

If the annotation is required, then I think the Changelog tab should be hidden, or a message should be shown on the page letting the user know that the annotation is not added.

So is it a bug, the documentation is wrong or what needs to be done?

**Comment by radoslaw-sz** [comment] 2023-11-07 18:05
@alexhampu  oh, ok, I think I got you. In other words - if annotations is required for a plugin, then you expect that instead of throwing an error there will be an info about adding required annotation?

**Comment by alexhampu** [comment] 2023-11-07 18:06
Yes, that would be more helpful, so the users know why the changelog is not shown. A lot of other plugins do it this way.

**Comment by radoslaw-sz** [comment] 2023-11-07 18:22
That's true :) I will prepare a fix in next days.

**Comment by radoslaw-sz** [comment] 2023-11-07 19:35
> As an update, now I have the CHANGELOG.md in my repository, but haven't added any of the annotations added to the project's catalog file, however it still throws an error.
> 
> ![image](https://user-images.githubusercontent.com/21214654/280553822-a87c217c-6e5f-4ae7-be84-dbbd201401f1.png)
> 
> When looking over the backstage server logs, I have the following message:
> 
> ```
> {"code":"ENOENT","errno":-2,"level":"error","message":"Request failed with status 500 ENOENT: no such file or directory, open 'https://github.com/private-team/private-project/tree/master/CHANGELOG.md'","path":"https://github.com/private-team/private-project/tree/master/CHANGELOG.md","service":"backstage","stack":"Error: ENOENT: no such file or directory, open 'https://github.com/private-team/private-project/tree/master/CHANGELOG.md'\n at Object.openSync (node:fs:603:3)\n at Object.readFileSync (node:fs:471:35)\n at readChangelogFile (/app/node_modules/@rsc-labs/backstage-changelog-plugin-backend/dist/index.cjs.js:21:41)\n at /app/node_modules/@rsc-labs/backstage-changelog-plugin-backend/dist/index.cjs.js:92:30\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"open","type":"errorHandler"}
> ```
> 
> When I access the url from the logs, the file exists, and it's valid as I use the structure from keepachangelog.
> 
> Does this plugin try to access the CHANGELOG.md by doing a get that URL? Because this won't work as the repository is private.

I also probably found a bug related to that - thanks for raising it. I will include fix for this also.

**Comment by radoslaw-sz** [comment] 2023-11-08 18:45
hi @alexhampu - please kindly check the latest releases (both frontend and backend have been changed). I hope I covered all issues.
For convenience, I also introduced two functions which might be useful, more info here: https://github.com/RSC-Labs/backstage-changelog-plugin#check-if-annotations-are-ok

**Comment by alexhampu** [comment] 2023-11-09 07:56
Without adding any annotation the plugin works correctly now, thank you! I haven't tested the 2 methods yet, but I will be able to do it next week, if there is any issue with those I will open a new issue.

**Comment by daneah** [comment] 2023-11-09 11:07
I'll check on this today when I can as well.

**Comment by radoslaw-sz** [comment] 2023-11-12 12:03
hi @alexhampu  @daneah ,
As this issue has spread to other issues, I would like to propose to close it as initial problem (react error) is now gone and some others errors also got fixes (but not yet confirmed if working).
I will appreciate if you could raise separated issue if something is wrong.

If you disagree, please kindly reopen this issue - at this moment I am closing it.

**Closed by radoslaw-sz** 2023-11-12 12:03 UTC
